const fs = require('fs');

const path = 'lib/academy/db.ts';
let code = fs.readFileSync(path, 'utf8');

const newCourses = `
  {
    id: 'course_glucosa_001',
    slug: 'monitorea-tu-glucosa-con-confianza',
    title: 'Monitorea tu glucosa con confianza',
    subtitle: 'Cómo medir, registrar y comprender tus resultados de forma correcta y segura.',
    shortDescription: 'Aprende a utilizar correctamente un glucómetro, conocer las bases del monitoreo continuo y registrar tus resultados sin convertir una lectura aislada en un diagnóstico. Identifica errores frecuentes y reconoce cuándo debes comunicarte con tu equipo de salud.',
    description: 'Aprende a utilizar correctamente un glucómetro, conocer las bases del monitoreo continuo y registrar tus resultados sin convertir una lectura aislada en un diagnóstico. Identifica errores frecuentes y reconoce cuándo debes comunicarte con tu equipo de salud.',
    category: 'bienestar',
    categoryLabel: 'Bienestar & Fisiología',
    level: 'Introductorio',
    durationMinutes: 45,
    lessonCount: 9,
    status: 'draft',
    accessType: 'free',
    launchStatus: 'published',
    previewEnabled: true,
    price: 0,
    compareAtPrice: 0,
    currency: 'MXN',
    instructor: {
      name: OFFICIAL_INSTRUCTOR.name,
      title: OFFICIAL_INSTRUCTOR.credentials,
      license: OFFICIAL_INSTRUCTOR.professionalLicense,
      institution: OFFICIAL_INSTRUCTOR.institution,
      avatarUrl: OFFICIAL_INSTRUCTOR.profileImage,
    },
    image: '/images/masterclasses/glucosa.webp',
    imageFallback: '/images/masterclasses/glucosa.png',
    imageAlt: 'Monitorea tu glucosa con confianza',
    imageWidth: 1586,
    imageHeight: 992,
    imagePosition: 'center',
    imagePriority: false,
    coverImage: '/images/masterclasses/glucosa.webp',
    coverAlt: 'Monitorea tu glucosa con confianza',
    disclaimerShort: 'Contenido educativo. No sustituye una consulta médica ni establece una relación médico-paciente.',
    disclaimerLong: 'El contenido de esta masterclass tiene fines exclusivamente educativos e informativos. No sustituye una consulta médica. No modifique sus tratamientos.',
    learningOutcomes: [],
    targetAudience: ['Personas con diabetes tipo 1', 'Personas con diabetes tipo 2', 'Familiares o cuidadores', 'Personas que comienzan a utilizar glucómetro', 'Usuarios de monitoreo continuo que necesitan comprender conceptos básicos'],
    includedFeatures: ['Registro imprimible de glucosa', 'Lista de preparación del equipo', 'Guía de errores frecuentes', 'Hoja de preguntas para la consulta médica'],
    faqs: [],
    modules: [],
  },
  {
    id: 'course_presion_001',
    slug: 'presion-arterial-midela-bien-en-casa',
    title: 'Presión arterial: mídela bien en casa',
    subtitle: 'Una técnica correcta puede transformar la utilidad de cada lectura.',
    shortDescription: 'Aprende a elegir un equipo adecuado, utilizar el brazalete correcto, preparar tu cuerpo y adoptar la postura necesaria para obtener mediciones más confiables. Descubre cómo registrar tus resultados y qué situaciones requieren atención médica.',
    description: 'Aprende a elegir un equipo adecuado, utilizar el brazalete correcto, preparar tu cuerpo y adoptar la postura necesaria para obtener mediciones más confiables. Descubre cómo registrar tus resultados y qué situaciones requieren atención médica.',
    category: 'bienestar',
    categoryLabel: 'Bienestar & Fisiología',
    level: 'Introductorio',
    durationMinutes: 40,
    lessonCount: 10,
    status: 'draft',
    accessType: 'free',
    launchStatus: 'published',
    previewEnabled: true,
    price: 0,
    compareAtPrice: 0,
    currency: 'MXN',
    instructor: {
      name: OFFICIAL_INSTRUCTOR.name,
      title: OFFICIAL_INSTRUCTOR.credentials,
      license: OFFICIAL_INSTRUCTOR.professionalLicense,
      institution: OFFICIAL_INSTRUCTOR.institution,
      avatarUrl: OFFICIAL_INSTRUCTOR.profileImage,
    },
    image: '/images/masterclasses/presion.webp',
    imageFallback: '/images/masterclasses/presion.png',
    imageAlt: 'Presión arterial: mídela bien en casa',
    imageWidth: 1586,
    imageHeight: 992,
    imagePosition: 'center',
    imagePriority: false,
    coverImage: '/images/masterclasses/presion.webp',
    coverAlt: 'Presión arterial: mídela bien en casa',
    disclaimerShort: 'Contenido educativo. No sustituye una consulta médica ni establece una relación médico-paciente.',
    disclaimerLong: 'El contenido de esta masterclass tiene fines exclusivamente educativos e informativos. No sustituye una consulta médica. No modifique sus tratamientos.',
    learningOutcomes: [],
    targetAudience: [],
    includedFeatures: ['Registro semanal de presión arterial', 'Infografía de postura correcta', 'Lista de errores comunes', 'Guía para preparar las lecturas antes de una consulta'],
    faqs: [],
    modules: [],
  },
  {
    id: 'course_sueno_001',
    slug: 'dormir-mejor-energia-enfoque-y-rendimiento',
    title: 'Dormir mejor: energía, enfoque y rendimiento',
    subtitle: 'Un sistema práctico para construir noches más reparadoras y días con mayor claridad.',
    shortDescription: 'Comprende cómo funcionan el sueño y el ritmo circadiano. Aprende a organizar la luz, los horarios, el ejercicio, la cafeína, el ambiente y tu rutina nocturna para favorecer un descanso de mejor calidad y apoyar tu energía y concentración durante el día.',
    description: 'Comprende cómo funcionan el sueño y el ritmo circadiano. Aprende a organizar la luz, los horarios, el ejercicio, la cafeína, el ambiente y tu rutina nocturna para favorecer un descanso de mejor calidad y apoyar tu energía y concentración durante el día.',
    category: 'bienestar',
    categoryLabel: 'Bienestar & Fisiología',
    level: 'Intermedio',
    durationMinutes: 90,
    lessonCount: 12,
    status: 'coming_soon',
    accessType: 'lifetime',
    launchStatus: 'coming_soon',
    previewEnabled: false,
    price: 0,
    compareAtPrice: 0,
    currency: 'MXN',
    instructor: {
      name: OFFICIAL_INSTRUCTOR.name,
      title: OFFICIAL_INSTRUCTOR.credentials,
      license: OFFICIAL_INSTRUCTOR.professionalLicense,
      institution: OFFICIAL_INSTRUCTOR.institution,
      avatarUrl: OFFICIAL_INSTRUCTOR.profileImage,
    },
    image: '/images/masterclasses/sueno.webp',
    imageFallback: '/images/masterclasses/sueno.png',
    imageAlt: 'Dormir mejor: energía, enfoque y rendimiento',
    imageWidth: 1586,
    imageHeight: 992,
    imagePosition: 'center',
    imagePriority: false,
    coverImage: '/images/masterclasses/sueno.webp',
    coverAlt: 'Dormir mejor: energía, enfoque y rendimiento',
    disclaimerShort: 'Contenido educativo. No sustituye una consulta médica ni establece una relación médico-paciente.',
    disclaimerLong: 'El contenido de esta masterclass tiene fines exclusivamente educativos e informativos. No sustituye una consulta médica. No modifique sus tratamientos.',
    learningOutcomes: [],
    targetAudience: ['Adultos que desean mejorar hábitos de sueño', 'Personas con horarios irregulares', 'Profesionales con cansancio relacionado con malos hábitos de descanso', 'Personas que buscan una rutina nocturna más consistente'],
    includedFeatures: ['Diario de sueño de 14 días', 'Lista de preparación del dormitorio', 'Plantilla de rutina nocturna', 'Planificador de horarios', 'Cuestionario de hábitos'],
    faqs: [],
    modules: [],
  }
];`;

code = code.replace(/export const INITIAL_COURSES: Course\[\] = \[/, 'export const INITIAL_COURSES: Course[] = [' + newCourses);

fs.writeFileSync(path, code);
